<a href="https://colab.research.google.com/github/leemutai/Intro_to_datascience/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define two NumPy arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Addition
print(x + y)  # Element-wise addition
print(np.add(x, y))  # Same as above

# Subtraction
print(x - y)  # Element-wise subtraction
print(np.subtract(x, y))  # Same as above

# Multiplication
print(x * y)  # Element-wise multiplication
print(np.multiply(x, y))  # Same as above

# Scalar multiplication
print(2 * y)  # Scalar multiplication with 2
print(3 * x)  # Scalar multiplication with 3

# Division
print(x / y)  # Element-wise division
print(np.divide(x, y))  # Same as above

# Square root
print(np.sqrt(x))  # Square root of each element in x


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[10. 12.]
 [14. 16.]]
[[ 3.  6.]
 [ 9. 12.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
