<a href="https://colab.research.google.com/github/leemutai/Intro_to_datascience/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Define two NumPy arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Addition
print(x + y)  # Element-wise addition
print(np.add(x, y))  # Same as above

# Subtraction
print(x - y)  # Element-wise subtraction
print(np.subtract(x, y))  # Same as above

# Multiplication
print(x * y)  # Element-wise multiplication
print(np.multiply(x, y))  # Same as above

# Scalar multiplication
print(2 * y)  # Scalar multiplication with 2
print(3 * x)  # Scalar multiplication with 3

# Division
print(x / y)  # Element-wise division
print(np.divide(x, y))  # Same as above

# Square root
print(np.sqrt(x))  # Square root of each element in x


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[10. 12.]
 [14. 16.]]
[[ 3.  6.]
 [ 9. 12.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [3]:
import pandas as pd
from pandas import Series, DataFrame# Series and DataFrame are two structures
#avalaible in python series
import numpy as np
import pandas as pd
mip = pd.Series([5,4,3,2,1])
print(mip)
print(mip.values)#similar to dictionary

0    5
1    4
2    3
3    2
4    1
dtype: int64
[5 4 3 2 1]


In [ ]:
import numpy as np
import pandas as pd
mip = pd.Series([5,4,3,2,1])# a simple series
print(mip) #A series is represented by index on the left and values on the right
print(mip.values)#similar to dictionary
series print(mip.index)#return index values of the series
print(mip.index)#returns the index values of the series
ieeya = pd.series([5,4,3,2,1,-7,-29])